### ISSUE TITLE
Build failure due to InfluxDB change their repository

### ISSUE THREAD

**Issue by cy-lee** [skyrings/skyring-common#1]
Hello,

Two files need to change their import URL:

skyring-common/monitoring/influxdbmanager/influxdb_manager.go
skyring-common/db/db.go

"github.com/influxdata/influxdb/client"

**Comment by shtripat** [comment]
We refer influxdb as vendor and attached with specific version as below
- package: github.com/influxdb/influxdb
  version: 8fe2469c75edce4909c71f931332c7e74d3f08ea

Till now we dont see a failure in our setup. By any chance this also would fails and we need to correct?

**Comment by cy-lee** [comment]
Here is reproduce steps:
- mkdir -p ${GOPATH}/github.com/skyrings/
- cd ${GOPATH}/github.com/skyrings/
- git clone https://review.gerrithub.io/skyrings/skyring
- cd ${GOPATH}
- go get ./...
- cd ${GOPATH}/github.com/skyrings/skyring
- make

Do I missing something ?

ubuntu@cy-desktop:~/prj/go-workspace$ export GOPATH=`pwd`  
ubuntu@cy-desktop:~/prj/go-workspace$ go get ./...  
package github.com/codegangsta/cli
        imports github.com/codegangsta/negroni
        imports github.com/gorilla/context
        imports github.com/gorilla/mux
        imports github.com/gorilla/websocket
        imports github.com/kidstuff/mongostore
        imports github.com/gorilla/securecookie
        imports github.com/gorilla/sessions
        imports gopkg.in/mgo.v2
        imports gopkg.in/mgo.v2/bson
        imports github.com/mqu/openldap
        imports github.com/natefinch/pie
        imports github.com/op/go-logging
        imports github.com/sbinet/go-python
        imports github.com/skyrings/skyring-common/conf
        imports github.com/skyrings/skyring-common/tools/logger
        imports github.com/skyrings/skyring-common/tools/gopy
        imports github.com/skyrings/skyring-common/dao
        imports github.com/skyrings/skyring-common/models
        imports github.com/skyrings/skyring-common/monitoring
        imports github.com/skyrings/skyring-common/tools/uuid
        imports github.com/skyrings/skyring-common/db
        imports github.com/influxdb/influxdb/client
        imports github.com/influxdb/influxdb/client
        imports github.com/influxdb/influxdb/client: code in directory /home/ubuntu/prj/go-workspace/src/github.com/influxdb/influxdb/client expects import "github.com/influxdata/influxdb/client"
ubuntu@cy-desktop:~/prj/go-workspace$ make
make: **\* No targets specified and no makefile found.  Stop.
ubuntu@cy-desktop:~/prj/go-workspace$ cd src/g
github.com/ golang.org/ gopkg.in/  
ubuntu@cy-desktop:~/prj/go-workspace$ cd src/github.com/
codegangsta/ gorilla/     influxdb/    kidstuff/    marpaia/     mqu/         natefinch/   op/          sbinet/      skyrings/  
ubuntu@cy-desktop:~/prj/go-workspace$ cd src/github.com/skyrings/skyring
ubuntu@cy-desktop:~/prj/go-workspace/src/github.com/skyrings/skyring$ ls
apps  authprovider  backend  build-aux  conf  event  glide.yaml  LICENSE  main.go  Makefile  misc  nodemanager  README.md  skyring-setup.sh  skyring.spec  skyringutils
ubuntu@cy-desktop:~/prj/go-workspace/src/github.com/skyrings/skyring$ make
Doing checkdeps
Doing getversion
Doing getdeps
Doing vet
authprovider/ldap/ldapauth.go:607: github.com/skyrings/skyring-common/models.Directory composite literal uses unkeyed fields
Doing fmt
Doing lint
Doing pybuild
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/skyring
copying skyring/**init**.py -> build/lib.linux-x86_64-2.7/skyring
copying skyring/saltwrapper.py -> build/lib.linux-x86_64-2.7/skyring
Doing test
../skyring-common/db/db.go:23:2: code in directory /home/ubuntu/prj/go-workspace/src/github.com/influxdb/influxdb/client expects import "github.com/influxdata/influxdb/client"
make: **\* [test] Error 1
ubuntu@cy-desktop:~/prj/go-workspace/src/github.com/skyrings/skyring$

**Comment by shtripat** [comment]
So we have vendor enabled.
So first time once you clone the repo, you need to run "make vendor-update"
and then run "make".

This flow should not break anything.

~Shubhendu
